services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: stockmarket_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  app1: &app_base
    build: .
    environment:
      DB_URL: "jdbc:postgresql://db:5432/stockmarket_db"
      DB_USER: "user"
      DB_PASSWORD: "password"
    depends_on:
      - db
    restart: always

  app2:
    <<: *app_base

  app3:
    <<: *app_base

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - app1
      - app2
      - app3